### ISSUE TITLE
Eval fail with additional meta

### ISSUE THREAD

**Issue by FrancisMahony** [rick-jennings/phable#4]
Through some trial and error I found that making a request through eval would error if I added additional grid meta. Simply removing the additional grid meta would work correctly.

Also, how does one get the stack trace on an error? Currently using this in JupyterLab, I don't receive any explicit errors, just an empty grid/dataframe.

**Comment by rick-jennings** [comment]
Hi Francis,

Are you using Phable version 0.1.10?  

If not, I would first recommend you use version 0.1.10.  Now we have a much simpler method parameter than before which is just a Haystack filter within a Python str.
https://github.com/rick-jennings/phable/blob/main/phable/client.py#L210

Also, please review the v0.1.10 CHANGELOG if you have not already done so:
https://github.com/rick-jennings/phable/blob/main/CHANGELOG.md

I might need to dig into the source code some more, but I don't think we throw an exception if you use the Eval Op and get nothing in return.  We might consider adding exceptions similar to what we do with the Read Op.
https://github.com/rick-jennings/phable/blob/main/phable/client.py#L124

Please let me know what you think and I would be happy to making a future enhancement to Phable.

Thanks,
Rick

**Comment by rick-jennings** [comment]
We changed the API design so that Client.eval() accepts a str describing a Haystack filter instead of a Grid.  This should make it easier to use the API.

I am not sure how exactly JupyterLab shows the stack trace.  Typically I run Python scripts on my terminal and have no issue seeing the stack trace.

If you are able to find a way to send to us the stack trace that would be helpful.  Or please let us know under what conditions you think it might make sense for us to raise an exception and we will look into adding support for that.  

In some upcoming work we plan on improving/adding exceptions.  I will consider your earlier feedback some more too. 
 Thanks.
